In [1]:
import pandas as pd

In [2]:
# pip install xlrd

In [3]:
df = pd.read_excel(r"C:\Users\paula\01_Ironhack\projects\quest shark attacks\coral-reefs_shark-attack\GSAF5.xls")

In [7]:
df.shape

(6969, 23)

In [74]:
df.head(20)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25 Feb-2024,2024.0,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,...,Tiger shark,"WA Today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14 Feb-2024,2024.0,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,...,"Bull shark, 7'","Times of India, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,04-Feb-2024,2024.0,Provoked,TRINIDAD,NaN,NaN,Spearfishing,male,M,NaN,...,Blacktip reef shark,"Trinidad Guardian, 2/11/2014",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,29 Jan-2024,2024.0,Unprovoked,AUSTRALIA,New South Wales,"Elizabeth Bay, Sydney Harbor",Swimming,Lauren O'Neill,F,29,...,Bull shark,"Nine News, 12/31/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,15 Jan-2024,2024.0,Unprovoked,BAHAMAS,Paradise Island,Paradise Island Resort,Swimming,male,M,10,...,NaN,"Caribbean Loop News, 1/15;2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,09-Jan-2024,2024.0,Unprovoked,AUSTRALIA,South Australia,"Walkers Beach, Elliston",Surfing,Murray Adams,M,64,...,White shark,"A. Currie, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,05-Jan-2024,2024.0,Provoked,SOUTH AFRICA,Eastern Cape Province,Papiesfontein,Fishing,male,M,62,...,Raggedtooth shark,Jacaranda fm. 12/6/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,30 Dec-2023,2023.0,Unprovoked,USA,Hawaii,"Baby Beach, Maui",Surfing,Jason Carter,M,39,...,NaN,"Surfer, 12/31/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,29 Dec-2023,2023.0,Unprovoked,MEXICO,Sonora,"Tojahui Beach, Yavaros, Huatabampo",Free diving,Víctor Alejandro “N”,M,22,...,White shark,"EuroESEuro, 12/31/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28 Dec-2023,2023.0,Unprovoked,AUSTRALIA,South Australia,Ethel Beach,Surfing,Khai Cowley,M,15,...,"White shark, 13'","S. DeMarchi, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,25 Dec-2023,2023.0,Unprovoked,AUSTRALIA,New South Wales,Old Bar,Surfing,Julian McLennan,M,16,...,NaN,"9 News, 12/26/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,24-Dec-2023,2023.0,Unprovoked,AUSTRALIA,Western Australia,Wedge Island,Foil Boarding,Troy Brown,M,46,...,Broze whaler?,"9 News, 12/25/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,18 Dec-2023,2023.0,Unprovoked,NEW ZEALAND,South Island,Riverton,Wading,female,F,21,...,Sevengill shark,"NZ Herald, 12/18/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,14 Dec-2023,2023.0,Questionable,MEXICO,Guerrero,"Playa Quieta, Ixtapa, Zihuatanejo",Swimming,Joseph Leopold Bynens,M,66,...,Shark involment not confirmed,"EL Pais, 12/15/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,14 Dec-2023,2023.0,Questionable,MEXICO,Guerrero,"Playa Quieta, Ixtapa, Zihuatanejo",Swimming,Valerie Haurowitz,F,52,...,Shark involment not confirmed,"EL Pais, 12/15/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,08 Dec-2023,2023.0,Unprovoked,AUSTRALIA,Queensland,1770,Snorkeling,Matteo Mariotti,M,20,...,NaN,"B. Myatt, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,04 Dec-2023,2023.0,Unprovoked,BAHAMAS,New Providence Isoad,Sandals Resort,Paddle boarding,Lauren Erickson Van Wart,F,44,...,NaN,"NBC News, 12/4/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df.sample(20)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
3161,08-Jul-1992,1992.0,Unprovoked,BRAZIL,Maranhão,"Praia da Marcela, São Marcos Bay",Surfing,L.G,M,NaN,...,NaN,M. Szpilman,1992.07.08.b-LG.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1992.07.08.b,1992.07.08.b,3781.0,NaN,NaN
5069,Between 01-Aug-1951 & 08-Aug-1951,1951.0,Unprovoked,COLUMBIA,Caribbean Sea,Cartegena,Bathing,"4 people killed in the past week, others injured",NaN,NaN,...,NaN,"New York Times, 8/9/1951; V.M. Coppleson (1958...",1951.08.00-Cartagena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1951.08.00,1951.08.00,1873.0,NaN,NaN
1906,2008.01.30,2008.0,Provoked,JAPAN,Tokyo Bay,NaN,Diving,NaN,M,NaN,...,"Goblin shark, 4.2'",L Compagno,2008.01.30-GoblinShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.01.30,2008.01.30,5036.0,NaN,NaN
4064,19-Aug-1969,1969.0,Provoked,USA,Florida,"Marathon, Monroe County",Fishing,Jack Horner,M,adult,...,"Lemon shark, 9'","Tri-City Herald, 4/21/1969",1969.04.19-Horner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1969.04.19,1969.04.19,2878.0,NaN,NaN
5461,13-Nov-1937,1937.0,Sea Disaster,USA,North Carolina,Off Cape Hatteraa,"Tzenny Chandris, a Greek freighter laden with ...",3 crewmen,M,NaN,...,NaN,"Stevens Point Journal, 11/15/1937; TIME, 11/22...",1937.11.13-Tzenny-Chandris.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1937.11.13,1937.11.13,1481.0,NaN,NaN
6423,1883,1883.0,Unprovoked,PACIFIC OCEAN,NaN,NaN,Fishing,"male, a cook",M,NaN,...,14' shark,"Freeborn County Standard, 11/14/1883",1883.00.00.d-cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1883.00.00.d,1883.00.00.d,520.0,NaN,NaN
438,30-Nov-2019,2019.0,Unprovoked,AUSTRALIA,Queensland,Bargara,Snorkeling,male,M,30,...,NaN,"K.McMurray, TrackingSharks.com",2019.11.30.a-Bargara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2019.11.30.a,2019.11.30.a,6504.0,NaN,NaN
4621,30-Apr-1960,1960.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Amanzimtoti,Treading water,Mike Hely,M,16,...,"White shark, 2.1 m [7'] based on tooth pattern","M. Hely, E. Kerns, M. Levine, GSAF; G.D. Camp...",1960.04.30-Hely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1960.04.30,1960.04.30,2321.0,NaN,NaN
4073,26-Dec-1968,1968.0,Provoked,AUSTRALIA,New South Wales,"Marineland Aquarium, Manley, Sydney",Feeding mullet to sharks,Peter Jones,M,27,...,"Grey nurse shark, 10'","The Age, 12/27/1968",1968.12.26-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.12.26,1968.12.26,2869.0,NaN,NaN
1125,27-Aug-2014,2014.0,Unprovoked,USA,South Carolina,"Surfside Beach, Horry County",Standing,female,F,NaN,...,NaN,"C. Creswell, GSAF",2014.08.27.a-Surfside.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.27.a,2014.08.27.a,5817.0,NaN,NaN
2931,09-Feb-1996,1996.0,Unprovoked,PAPUA NEW GUINEA,Madang Province,Madang,NaN,College student,NaN,NaN,...,NaN,"Sunday Mail (QLD), 2/11/1996, p.28",1996.02.10.b-CollegeStuden.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1996.02.10.b,1996.02.10.b,4011.0,NaN,NaN
2779,Reported 16-Sep-1998,1998.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Kowie River,Fishing / washing bait off hands,Grant Rielly,M,NaN,...,NaN,"Daily Dispatch, 9/16/1998",1998.09.16.R-Rielly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.09.16.R,1998.09.16.R,4163.0,NaN,NaN
5075,Reported 09-May-1951,1951.0,Provoked,ITALY,Naples Province,"Torre del Greco, Naples",NaN,NaN,NaN,NaN,...,NaN,"C. Moore, GSAF",1951.05.09.R-Naples.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1951.05.09.R,1951.05.09.R,1867.0,NaN,NaN
3272,12-Nov-1989,1989.0,Invalid,USA,Hawaii,"Ehukai Beach Park, Sunset Beach, O'ahu","Wading, knocked down & swept away by large waves",Edward Malek,M,NaN,...,Shark involvement prior to death was not confi...,"J. Borg, p.78; L. Taylor (1993), pp.108-109",1989.11.12-Malek.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1989.11.12,1989.11.12,3670.0,NaN,NaN
206,Reported 10-Feb-2022,2022.0,Provoked,BAHAMAS,NaN,NaN,NaN,Eniko Hart,F,37,...,Nurse shark,"K. McMurray, TrackingSharks.com",2022.02.10.R-Hart.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2022.02.10.R,2022.02.10.R,6736.0,NaN,NaN
1849,13-Jul-2008,2008.0,Invalid,USA,North Carolina,"Carolina Beach, New Hanover County",Body surfing,Donald Griffin,M,52,...,Shark involvement not confirmed,"C. Creswell, GSAF",2008.07.13-Griffin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.07.13,2008.07.13,5093.0,NaN,NaN
2337,06-Nov-2003,2003.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Karridene,Surf skiing,2 people on ski,NaN,NaN,...,White shark,Natal Sharks Board,2003.11.06.a-Karridene.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.11.06.a,2003.11.06.a,4605.0,NaN,NaN
3022,13-Dec-1994,1994.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Surfing,Tiago Costa de Lima,M,NaN,...,NaN,JCOnline; M. Szpilman,1994.12.13-TiagoCostaDaLima.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1994.12.13,1994.12.13,3920.0,NaN,NaN
2444,16-Sep-2002,2002.0,Unprovoked,USA,Hawaii,"Hideaways Beach, Princeville, Kaua'i",Body boarding,NaN,NaN,NaN,...,NaN,Hawaii Department of Land and Natural Resources,2002.09.16.a-Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2002.09.16.a,2002.09.16.a,4498.0,NaN,NaN
4390,04-Feb-1963,1963.0,Invalid,USA,Florida,Off Key West,"S.S. Marine Sulphur Queen, laden with molten s...",2 males,M,NaN,...,Shark involvement prior to death was not confi...,"NY Journal of Commerce, 3/29/1963;Wikipedia",1963.02.04-MarineSulphurQueen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1963.02.04,1963.02.04,2552.0,NaN,NaN

In [8]:
df.tail(26)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
6943,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN
6944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df.isna().sum()

Date                25
Year                27
Type                43
Country             75
State              507
Location           590
Activity           611
Name               245
Sex                604
Age               3019
Injury              60
Unnamed: 11        587
Time              3551
Species           3157
Source              44
pdf                170
href formula       150
href               173
Case Number        171
Case Number.1      172
original order     170
Unnamed: 21       6968
Unnamed: 22       6967
dtype: int64

In [64]:
df["Unnamed: 11"].sample(20)

3197        NaN
945           N
659           N
1327          N
2756        NaN
4636          N
6470          Y
4167          N
1607          N
2687          N
5200          Y
6805    UNKNOWN
4696        NaN
1215          N
3173          N
5148          Y
1541          N
4985          N
5971          Y
3825          N
Name: Unnamed: 11, dtype: object

In [9]:
df.Injury

0       Minor injuries to back, abdomen and legs
1                 No injury, shark bit surfboard
2                       Lacerations to left foot
3                                     Leg bitten
4                 Calf of lower left leg injured
                          ...
6964                                         NaN
6965                                         NaN
6966                                         NaN
6967                                         NaN
6968                                         NaN
Name: Injury, Length: 6969, dtype: object

In [66]:
df["Unnamed: 22"].notnull()

0       False
1       False
2       False
3       False
4       False
        ...
6964    False
6965    False
6966    False
6967    False
6968    False
Name: Unnamed: 22, Length: 6969, dtype: bool

In [68]:
df[df["Unnamed: 22"] != "NaN"]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25 Feb-2024,2024.0,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,...,Tiger shark,"WA Today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14 Feb-2024,2024.0,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,...,"Bull shark, 7'","Times of India, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.eq(" ").sum() # 1 empty space

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          1
Name              0
Sex               0
Age               2
Injury            1
Unnamed: 11       0
Time              2
Species           7
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [28]:
df.eq("  ").sum() # 2 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               1
Injury            0
Unnamed: 11       0
Time              1
Species           1
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [34]:
df.eq("   ").sum() # 3 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          1
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              1
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [36]:
df.eq("    ").sum() # 4 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [38]:
df.eq("     ").sum() # 5 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [40]:
df.eq("      ").sum() # 6 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [42]:
df.eq("       ").sum() # 7 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [44]:
df.eq("        ").sum() # 8 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64

In [46]:
df.eq("         ").sum() # 9 empty spaces

Date              0
Year              0
Type              0
Country           0
State             0
Location          0
Activity          0
Name              0
Sex               0
Age               0
Injury            0
Unnamed: 11       0
Time              0
Species           0
Source            0
pdf               0
href formula      0
href              0
Case Number       0
Case Number.1     0
original order    0
Unnamed: 21       0
Unnamed: 22       0
dtype: int64